# Generated by Django 5.2 on 2025-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
